apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "mymutatingwebhook.example.com"
webhooks:
- name: "mymutatingwebhook.example.com"
  objectSelector:
    matchLabels:
      app: cert-manager
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
  clientConfig:
    service:
      namespace: "kube-system"
      name: "cert-manager-wi-webhook"
      path: "/webhook"
    caBundle: "cGxhY2Vob2xkZXIK"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-wi-webhook
  namespace: kube-system
  labels:
    app: cert-manager-wi-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-wi-webhook
  template:
    metadata:
      labels:
        app: cert-manager-wi-webhook
    spec:
      containers:
      - name: mutatingwebhook
        image: wardviaene/mutatingwebhook-example
        ports:
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-wi-webhook
  namespace: kube-system
spec:
  selector:
    app: mutatingwebhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
